### PR TITLE
BUGFIX: Use default storage instead of storage #1

### PR DESCRIPTION
**Pull request by alexanderschnitzler**
Fixes: #101

### CODE REVIEW

**Comment by franzholz** [comment]
This patch leads to an error message:

**Call to a member function getFileInfo() on null
in /jambage.com/path/typo3conf/ext/tt_products/model/field/class.tx_ttproducts_field_media.php line 146**

                foreach ($sysfileRowArray as $fileUid => $sysfileRow) {
                    $resourceFactory = GeneralUtility::makeInstance(ResourceFactory::class);
                    $fileObj = $resourceFactory->getFileReferenceObject($sysfileRow['uid']);
                    $fileInfo = $storage->getFileInfo($fileObj);

                    if ($fal) {
                        $fileArray[$sysfileRow['uid']] = array_merge($fileInfo, $sysfileRow);
                        $keepFields = ['title', 'description', 'alternative'];
                        
                        
  Reason:
  
  `$storage = $storageRepository->getDefaultStorage();`
  
  This returns a null value for $storage!

**Comment by alexanderschnitzler** [comment]
It depends on your environment. What environment do you test this in? A TYPO3 installation without a storage that is marked default? That's highly unusal and unlikely to happen. But the possibility remains, just like with `findByUid(1)`.

**Comment by alexanderschnitzler** [comment]
If you want to be sure that you code works in environments you cannot control, I suggest something like this:

```php
$storage = $storageRepository->getDefaultStorage() ?? throw new \LogicException('The installation does not have a default storage configured.');
```

It's the responsibility of the user of your extension and of TYPO3 to configure at least one storage that is marked `default`.
And `getDefaultStorage()` is the default TYPO3 api here:

```php
    /**
     * Returns the Default Storage
     *
     * The Default Storage is considered to be the replacement for the fileadmin/ construct.
     * It is automatically created with the setting fileadminDir from install tool.
     * getDefaultStorage->getDefaultFolder() will get you fileadmin/user_upload/ in a standard
     * TYPO3 installation.
     */
    public function getDefaultStorage(): ?ResourceStorage
    {
        // ...
    }
```

**Comment by franzholz** [comment]
The Install Tool shows it to be set correctly:

`[BE][fileadminDir] = fileadmin/
`
However TYPO3 11.5.30 does not use it as default storage.

**Comment by franzholz** [comment]
In StorageRepository I see 

    public function getDefaultStorage(): ?ResourceStorage
    {
        $allStorages = $this->findAll();
 debug ($allStorages, 'getDefaultStorage $allStorages');
 
        foreach ($allStorages as $storage) {

            if ($storage->isDefault()) {
                return $storage;
            }
        }
        return null;
    }
    
    
    
storageRecord:
_name	fileadmin/ (auto-created)
description	This is the local fileadmin/ directory. This storage mount has been created automatically by TYPO3._
 
isDefault	Boolean false


Therefore the fileadmin storage is not returned as a default storage.

**Comment by franzholz** [comment]
I cannot find any way to set the fileadmin as the default storage. Therefore I suggest to add the previous Storage-Id = 1 in the case when no default storage is available.

    $storage = $storageRepository->findByUid(1);

**Comment by alexanderschnitzler** [comment]
A storage is a database record in `sys_file_storage` which have a `is_default` flag. It's usually created on pid `0`. I didn't set up a new TYPO3 project for a long time but I am pretty sure that a record is created during the installation.

I am fine with trying to find a storage by uid 1 as a fallback though.

**Comment by franzholz** [comment]
New pull request:

https://github.com/franzholz/tt_products/pull/227

**Pull request merged**
