### PR TITLE
TASK: Run php cs fixer

### PR DESCRIPTION
**Pull request by alexanderschnitzler**
Hi,
here's the bigger change now, running php-cs-fixer on all files.

Let me know if you like the change and ping me to create the same PR for develop so you don't need to merge and resolve conflicts.

php-cs-fixer uses the `PER` coding style, formerly known as `PSR12`.

### CODE REVIEW

**Comment by franzholz** [comment]
Why is PER coding style neede?

Don't add the bug fix here. Make another issue for it.

**Comment by alexanderschnitzler** [comment]
> Why is PER coding style neede?

It's not needed, it's recommended to use a coding style you can automatically enforce through a tool like `php-cs-fixer` to have all code look the same and have better readability of the code. It's easier for contributors and yourself to focus on the actual logic change instead of the logic change and the change of style.

You can find more about it here: https://www.php-fig.org/per/coding-style/

> Don't add the bug fix here. Make another issue for it.

It's the same change I made a PR for last week: https://github.com/franzholz/tt_products/pull/211/files
You accepted the PR but then part of the change got reverted during your merges to develop and back to master.

Would you mind shortly committing it yourself? It's just one brace and master currently still contains a syntax error.

**Comment by franzholz** [comment]
I have commited the path 211 again.

The style guide allows some flexibility:

**Boolean operators between conditions MUST always be at the beginning or at the end of the line, not a mix of both.**

So I want to keep the boolean operators at the end of the line.  I have used it in this way for all the years.

**Comment by alexanderschnitzler** [comment]
Would that be the only problem you see with this patch? I can change that back.

**Comment by franzholz** [comment]
There is another thing:

**defined('TYPO3') || exit('Access denied.');**

There is no reason why "die" should be replaced by "exit".

**Comment by alexanderschnitzler** [comment]
I changed it back. There are additional rules that make sense. The reason for this change was a rule that replaces function aliases with their originals. Like `fputs` -> `fwrite`. And since `die` is just an alias of `exit`, the rule changed that as well.

See https://www.php.net/manual/en/aliases.php for reference.

**Comment by franzholz** [comment]
Which rules did you apply? I need this information in order to do the same with other versions and extensions.

**php php-cs-fixer.phar fix  ...**

**Comment by alexanderschnitzler** [comment]
I ran it through ddev:
 `ddev exec php-cs-fixer fix -vvv --diff`

But directly on the host is also possible:

`php php-cs-fixer.phar fix -vvv --diff`

**Comment by franzholz** [comment]
I cannot get this to do something.

```
[franz@franz-820 TYPO3]$ tools/php-cs-fixer/vendor/bin/php-cs-fixer fix -vvv --diff src  
PHP CS Fixer 3.41.1 Long Night by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.13
Loaded config default.
Using cache file ".php-cs-fixer.cache".
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  79 / 282 ( 28%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 158 / 282 ( 56%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 237 / 282 ( 84%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                   282 / 282 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error

Fixed 0 of 282 files in 0.027 seconds, 16.000 MB memory used

```

**Comment by alexanderschnitzler** [comment]
Without knowing what exactly you do I can recommend the following things:

### Install php-cs-fixer via composer 

```
composer require --dev friendsofphp/php-cs-fixer
```

That way, other can use the tool without installing it manually as a phar. `vendor/bin/php-cs-fixer` is then available to all contributors.

### Check out the default configuration file for `php-cs-fixer`

The default config file is `.php-cs-fixer.dist.php`. For `tt-products` its content is as follows:

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

$finder = (new \Symfony\Component\Finder\Finder())
    ->in(__DIR__)
    ->ignoreDotFiles(false)
    ->ignoreVCS(true)
    ->exclude([
        '.ddev',
        'public',
        'var',
        'vendor',
    ])
    ->name('/\.php$/')
;

// foreach ($finder->sortByName() as $file) {
//    /** @var SplFileInfo $file */
//    dump($file->getRealPath());
// }

$revertedSymfonyRules = [
    'cast_spaces' => [ // revert @Symfony
        'space' => 'none',
    ],
    'concat_space' => [ // revert @Symfony
        'spacing' => 'one',
    ],
    'increment_style' => false, // revert @Symfony
    'no_alias_language_construct_call' => false, // revert @Symfony
    'nullable_type_declaration_for_default_null_value' => [ // revert @Symfony
        'use_nullable_type_declaration' => true,
    ],
    'phpdoc_align' => false, // revert @Symfony
    'phpdoc_no_access' => false, // revert @Symfony
    'phpdoc_no_package' => false, // revert @Symfony
    'phpdoc_to_comment' => false, // revert @Symfony
    'single_line_comment_style' => true, // revert @Symfony
    'single_line_throw' => false, // revert @Symfony
    'yoda_style' => false, // revert @Symfony
];

$revertedPhpCsFixerRules = [
    'no_useless_else' => false,
    'no_superfluous_elseif' => false,
];

$revertedPHP81Rules = [
    'octal_notation' => false,
];

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(false)
    ->setRules(array_merge_recursive([
        '@DoctrineAnnotation' => true,
        '@PHP70Migration' => true,
        '@PHP71Migration' => true,
        '@PHP73Migration' => true,
        '@PHP74Migration' => true,
        '@Symfony' => true,
        'multiline_whitespace_before_semicolons' => [ // @PhpCsFixer
            'strategy' => 'new_line_for_chained_calls',
        ],
        'phpdoc_no_empty_return' => true, // @PhpCsFixer
        'operator_linebreak' => [ // adjust @Symfony
            'only_booleans' => true,
            'position' => 'end',
        ],
    ], $revertedPHP81Rules, $revertedPhpCsFixerRules, $revertedSymfonyRules))
    ->setFinder($finder)
;
```


This first part is responsible for defining which files are processed:

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

$finder = (new \Symfony\Component\Finder\Finder())
    ->in(__DIR__)
    ->ignoreDotFiles(false)
    ->ignoreVCS(true)
    ->exclude([
        '.ddev',
        'public',
        'var',
        'vendor',
    ])
    ->name('/\.php$/')
;

// foreach ($finder->sortByName() as $file) {
//    /** @var SplFileInfo $file */
//    dump($file->getRealPath());
// }
```

You can add the file, enable the commented foreach and execute it to see what files `symfony/finder` finds:
```
php .php-cs-fixer.dist.php
```

As soon as you made sure the finder finds all relevant files of your project you can add the configuration. You can copy the contents of tt-products and then run the fixer.

---

The reason why the fixer runs but skips all files might be because `php-cs-fixer` finds all php files by default but does not apply any rules. You can run the `php-cs-fixer` without a configuration file but then it expects you to add the rules option:

```
php php-cs-fixer.phar fix /path/to/project --rules=@PSR12
```

However, I suggest to use the configuration file because you can then finetune the set of rules you want to apply.

**Comment by franzholz** [comment]
So the composer installation must be executed from inside of the tt_products folder and not from anywhere else.

**vendor/bin/php-cs-fixer fix** 

Then this finally does the correct conversion!

It somehow did not use the `.php-cs-fixer.dist.php`  configuration file when I executed the `tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src`  command. Then it did just nothing.

**Pull request merged**
